<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="spyder" failures="1" tests="6" name="Default test(failed)" time="66.159" errors="0" timestamp="2024-05-07T13:23:02 IST">
  <testcase classname="sample.INvoicTest2" name="activatesim" time="0.025">
    <skipped/>
  </testcase> <!-- activatesim -->
  <testcase classname="sample.INvoicTest2" name="activatesim" time="0.012">
    <skipped/>
  </testcase> <!-- activatesim -->
  <testcase classname="sample.INvoicTest2" name="activatesim" time="0.01">
    <skipped/>
  </testcase> <!-- activatesim -->
  <testcase classname="sample.INvoicTest2" name="activatesim" time="0.01">
    <skipped/>
  </testcase> <!-- activatesim -->
  <testcase classname="sample.INvoicTest2" name="activatesim" time="0.012">
    <skipped/>
  </testcase> <!-- activatesim -->
  <testcase classname="sample.INvoicTest2" name="activatesim" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [login] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]">
      <![CDATA[java.lang.AssertionError: expected [login] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at sample.INvoicTest2.activatesim(INvoicTest2.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- activatesim -->
</testsuite> <!-- Default test(failed) -->
